# Generated by Django 5.1.6 on 2025-02-23 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True, max_length=300)),
                ('telephone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('contacts_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_book.contacts_list')),
            ],
        ),
    ]
